### ISSUE TITLE
Key signal

### ISSUE THREAD

**Issue by Shindd** [Shindd/Fault-detection-inceptionV3#2]
Current : We use space + q to capture spot image, but with 2 keys... it doesn`t work well

Suggest : Use only 1 key( only Q or S )

**Comment by JeongJuhyeon** [comment]
I've improved this part of the UI. Now when you press Enter, it will give a box that supports both the hotkeys as well as buttons. To me this looks like the best way to handle it. 지금 git 설치중이고 code를 제출해볼게요.

**Comment by JeongJuhyeon** [comment]
https://github.com/Shindd/Fault-detection-inceptionV3/commit/11906051bff1a8583c9fd13a66c0ee7f69f31a3a

**Comment by Shindd** [comment]
Close issue #3
